use_default_settings: true

server:
  secret_key: "RZ1fPdnW6BhoaFHihrcdcSZSgcG1Tp"

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  formats:
    - html
    - json

ui:
  static_use_hash: true

engines:
  - name: google
    engine: google
    shortcut: go
    disabled: false
  - name: bing
    engine: bing
    shortcut: bi
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
  - name: startpage
    engine: startpage
    shortcut: sp
    disabled: false
  - name: qwant
    engine: qwant
    shortcut: qw
    disabled: false
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false
